kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32083
        hostPort: 32083
        protocol: TCP
      - containerPort: 32230
        hostPort: 32230
        protocol: TCP
      - containerPort: 32235
        hostPort: 32235
        protocol: TCP
      - containerPort: 32240
        hostPort: 32240
        protocol: TCP
      - containerPort: 32245
        hostPort: 32245
        protocol: TCP
      - containerPort: 32250
        hostPort: 32250
        protocol: TCP
